# Kafka in KRaft-Modus (ohne separaten ZooKeeper-Server, einzig unterst√ºtzte Variante ab Kafka 4.0)
version: '3'
services:
  kafka:
    image: confluentinc/cp-kafka:8.1.1 # https://hub.docker.com/r/confluentinc/cp-kafka/
    hostname: kafka
    ports:
      - "9092:9092"
      - "29093:29093"  # Controller port
    environment:
      CLUSTER_ID: Mkp3OEVBNTcwNTJENdM2Qk  # Replace with random-uuid
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
